on: [push]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        uses: docker/build-push-action@v3
        with:
          push: false
          target: builder

      - name: Test
        uses: docker/build-push-action@v3
        with:
          push: false
          target: tester
