name: Check Secrets Vulnerabilities

on:
  # run it on push to the default repository branch
  # Only if there are changes on the 'python-flask directory
  push:
    branches: [main]
  pull_request:

env:
  REGISTRY: ghcr.io
  REPOSITORY_NAME: ${{ github.repository }}

jobs:
 check-secrets:
    name: Check Secrets Vulnerabilities
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Checkout Git-Secrets repository
        uses: actions/checkout@v3
        with:
          repository: awslabs/git-secrets
          path: './git-secrets'

      - name: Install Git-Secrets
        run: |
          cd ./git-secrets
          sudo make install
          export PATH="/usr/local/share/git-secrets:$PATH"
          cd -

      - name: Scan Git History
        run: git secrets --scan-history

      - name: Scan Repository
        run: git secrets --scan -r .
