name: Python Flask

on:
  # run it on push to the default repository branch
  # Only if there are changes on the 'python-flask directory
  push:
    branches: [main]
    paths:
    - python-flask/**
  pull_request:
    paths:
    - python-flask/**

env:
  REGISTRY: ghcr.io
  REPOSITORY_NAME: ${{ github.repository }}

jobs:
 build-ci-image:
    name: Build CI Image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build docker images
        run: make python-build

      - name: Check code style
        run: make python-style

      - name: Check code complexity
        run: make python-complexity

      - name: Run Tests
        run: make python-test
